site_name: Hostdon Documentetion
theme:
  name: material
  palette:
    primary: light bule
  font:
    text: BIZ UDPGothic
    code: Inconsolata
markdown_extensions:
  - admonition
plugins:
    - awesome-pages




copyright: "&copy; 2024 Hostdon / Auriga"